### ISSUE TITLE
关于移动端显示效果的问题

### ISSUE THREAD

**Issue by Rikka-Sei** [frostming/fxzhihu#1]
## 问题

在使用中，我发现在手机端预览时（redirect=no），依然显示为电脑版样式，移动端的阅读体验不佳。

## 现象

![图片](https://github.com/user-attachments/assets/5509276a-0e9f-4d9d-a5a8-9a9935d35873)

**Comment by Rikka-Sei** [comment]
目前进展
+ 在尝试部署 worker
+ (准备修复)

**Comment by frostming** [comment]
不用部署
```
pnpm dev
```
可以在本地开发

**Comment by Rikka-Sei** [comment]
好的
