### ISSUE TITLE
是否有计划支持 billboard？

### ISSUE THREAD

**Issue by ChrAlpha** [frostming/fxzhihu#16]
> 众所周知，在 2024 年的今天，非登录用户无法阅读知乎的答案，导致一些优质内容无法在互联网上分享，许多人只能选择转载或截图。 所以，我写了这个项目，**方便大家在社群里分享知乎的内容**。

支持 [知乎热榜](https://www.zhihu.com/billboard) 可能与项目初衷不符。但是从原知乎热榜里点进每个问题再替换 URL 也十分繁琐。倘若维护者有意支持我也愿意尝试贡献 PR。

**Comment by frostming** [comment]
不打算支持，如果你需要在你的频道中发整个热榜，可以自行写脚本替换 URL
除此之外我没想到使用的场景
