### ISSUE TITLE
部分页面的 instant view 失效，可能与包含 LaTeX 有关

### ISSUE THREAD

**Issue by GalaxySnail** [frostming/fxzhihu#24]
目前观察到失效的三个页面都包含 LaTeX，初步怀疑可能与此有关。

[1] https://www.fxzhihu.com/question/2214324880/answer/16366045437
[2] https://zhuanlan.fxzhihu.com/p/3313652433
[3] https://www.fxzhihu.com/question/611808133/answer/3119298190

**Comment by asukaminato0721** [comment]
我这里测试能看, 具体报错是啥.

![image](https://github.com/user-attachments/assets/9428e6fc-3799-4da7-b55d-5bd9413e460c)
![image](https://github.com/user-attachments/assets/b535eeba-a6c9-4589-b943-1409644cc93f)

**Comment by GalaxySnail** [comment]
我指的是 [instant view](https://instantview.telegram.org/)，不是 `?redirect=no`。这东西完全不透明，没有报错

**Comment by frostming** [comment]
There is no elegant way to display the equation images in instant view. But anyway it is fixed to not crash at least.
