### ISSUE TITLE
yue.css make avator flatten, maybe `!important` could solve it

### ISSUE THREAD

**Issue by asukaminato0721** [frostming/fxzhihu#26]
![image](https://github.com/user-attachments/assets/bc7775c1-6d52-4f72-881f-0636cc98012d)

now the avator becomes

![image](https://github.com/user-attachments/assets/aabeb3b3-87ad-41e5-871a-8e1b40f538cf)

100 x 132.85

<https://developer.mozilla.org/en-US/docs/Web/CSS/important>

**Comment by asukaminato0721** [comment]
example : <https://zhuanlan.fxzhihu.com/p/1755741138>

**Comment by frostming** [comment]
add `!important` to `height:100px` should work, can you open a PR?

**Comment by asukaminato0721** [comment]
![image](https://github.com/user-attachments/assets/913db381-cf4f-4cf8-a624-6abf9d0747aa)
