### ISSUE TITLE
add error report when json is invalid

### ISSUE THREAD

**Issue by asukaminato0721** [frostming/fxzhihu#32]
for example:

https://www.fxzhihu.com/question/3563017799/answer/27064833396

instead of plain error, returning an error page to show this page can't be visited is more helpful.

**Comment by frostming** [comment]
I've simply return the api response, feel free to contribute if you rather prefer to render it to HTML.

**Comment by asukaminato0721** [comment]
I just found out the preview can't show json. So I will make a PR to render it to HTML. So users can know the preview "worked".
