### ISSUE TITLE
本项目能否用于自部署？

### ISSUE THREAD

**Issue by ghost** [frostming/fxzhihu#41]
如题。首先请允许我表达对您工作的敬意和感激。

我希望能够自行在 Cloudflare 或者 Vercel、Netlify 等平台部署本项目，用于纯粹的个人、非营利性的浏览和分享。请问这样做是否符合本项目的规则要求？

期待您的回复。

此致。

**Comment by frostming** [comment]
当然可以，项目本身可以直接用Cloudflare Worker部署，至于其他平台就需要改造一下。

**Comment by ghost** [comment]
> 当然可以，项目本身可以直接用Cloudflare Worker部署，至于其他平台就需要改造一下。

感谢您的回复，祝项目越来越好。
