### ISSUE TITLE
use string template instead of regex replace?

### ISSUE THREAD

**Issue by asukaminato0721** [frostming/fxzhihu#8]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Template_literals#%E5%B8%A6%E6%A0%87%E7%AD%BE%E7%9A%84%E6%A8%A1%E6%9D%BF

so can remove one regex here.

```js
export function renderTemplate(template: string, data: Record<string, string>): string {
    return template.replace(/\{\{([^}]+)\}\}/g, (match, p1) => {
        return data[p1] || '';
    });
}
```

---

If ok, I could make a PR for it.

find <https://developers.cloudflare.com/workers/platform/limits/#worker-limits>, I hope string template won't be too slow.

**Comment by frostming** [comment]
This is to separate the template from the data. I initially considered using a string template, but I was worried it would make it hard to read.

**Comment by asukaminato0721** [comment]
mdn has an example of separate them

```js
function template(strings, ...keys) {
  return (...values) => {
    const dict = values[values.length - 1] || {};
    const result = [strings[0]];
    keys.forEach((key, i) => {
      result.push(dict[key], strings[i + 1]);
    });
    return result.join("");
  };
}

const t3Closure = template`I'm ${"name"}. I'm almost ${"age"} years old.`;
t3Closure({ name: "MDN", age: 30 }); // "I'm MDN. I'm almost 30 years old."
```

**Comment by frostming** [comment]
LGTM
